### ISSUE TITLE
Crash in RouteManager.GetAtmsInRegion

### ISSUE THREAD

**Issue by Kahtaf** [MogolInc/GlideAndroidSample#1]
Hi there, 

I found an issue with the Glide Android SDK. I have an asynctask asking for raw data on map camera change, similar to the sample shown here. When I zoomed out past a certain point, I got this crash:

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:325)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.StringIndexOutOfBoundsException: length=1137; index=1137
	at java.lang.String.charAt(Native Method)
	at com.mogolinc.glide.cloudsdk.Atms.decodePolyline(Atms.java:121)
	at com.mogolinc.glide.cloudsdk.Atms.<init>(Atms.java:61)
	at com.mogolinc.glide.cloudsdk.RouteManager.GetAtmsInRegion(RouteManager.java:508)
	at com.bitspice.automate.maps.GlideManager$fetchRegionAsyncTask.doInBackground(GlideManager.java:110)
```

**Comment by robert-calon** [comment]
Hi Kahtaf, and thanks for the feedback. Can you provide the map boundary that caused the crash?

**Comment by robert-calon** [comment]
Never mind, we've found the bug; it is server-side. We will shortly release an SDK update that handles the problem more gracefully, and push a server-side update this weekend.

**Comment by robert-calon** [comment]
Release 1.0.0-alpha5 is live, to handle the error gracefully, and I will close this issue as soon as the root cause is confirmed as fixed server-side.

Thanks again!

**Comment by Kahtaf** [comment]
Apologize for the late response, thanks for the quick turnaround!

**Comment by recalon** [comment]
All fixed.

**Comment by robert-calon** [comment]
This should be all fixed now. I'll close this issue once you can confirm.

**Comment by Kahtaf** [comment]
Just tried it out, seems to be fixed. Thanks!

**Comment by robert-calon** [comment]
Perfect. Our pleasure.
